import "../style2.css"
import "../src/css/basic-style.css"
import "../src/css/style_catalog.css"
import "../src/css/footer-style.css"
import "../src/css/header-style.css"
import "../src/css/card.css"

import "../src/js/preloader/preloader.js"
import "../src/js/cotalog/pagination.js"
import "../src/js/api/api.js"
import "../src/js/cotalog/cart.js"
import "../src/js/cotalog/cart-status.js"
import "../src/js/cotalog/favorite.js"
import "../src/js/cotalog/favorite-status.js"
import "../src/js/cotalog/catalog.js"
import "../src/js/cotalog/method.js"
import "../src/js/components/header.js"
import "../src/js/components/footer.js"